// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Request struct {
	ID          uuid.UUID
	Token       string
	Description string
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	SubmittedAt pgtype.Timestamptz
	RetrievedAt pgtype.Timestamptz
	Ciphertext  []byte
	Iv          []byte
	Status      string
}
