// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (token, description, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token, description, created_by, created_at, expires_at,
          submitted_at, retrieved_at, ciphertext, iv, status
`

type CreateRequestParams struct {
	Token       string
	Description string
	CreatedBy   string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.Token,
		arg.Description,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Ciphertext,
		&i.Iv,
		&i.Status,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = $1 AND created_by = $2
`

type DeleteRequestParams struct {
	ID        uuid.UUID
	CreatedBy string
}

func (q *Queries) DeleteRequest(ctx context.Context, arg DeleteRequestParams) error {
	_, err := q.db.Exec(ctx, deleteRequest, arg.ID, arg.CreatedBy)
	return err
}

const expirePendingRequests = `-- name: ExpirePendingRequests :execrows
UPDATE requests
SET status = 'expired'
WHERE status = 'pending'
  AND expires_at <= now()
`

func (q *Queries) ExpirePendingRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, token, description, created_by, created_at, expires_at,
       submitted_at, retrieved_at, ciphertext, iv, status
FROM requests
WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Ciphertext,
		&i.Iv,
		&i.Status,
	)
	return i, err
}

const getRequestByToken = `-- name: GetRequestByToken :one
SELECT id, token, description, created_by, created_at, expires_at,
       submitted_at, retrieved_at, ciphertext, iv, status
FROM requests
WHERE token = $1
`

func (q *Queries) GetRequestByToken(ctx context.Context, token string) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByToken, token)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Ciphertext,
		&i.Iv,
		&i.Status,
	)
	return i, err
}

const listRequestsByUser = `-- name: ListRequestsByUser :many
SELECT id, token, description, created_by, created_at, expires_at,
       submitted_at, retrieved_at, ciphertext, iv, status
FROM requests
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT 200
`

func (q *Queries) ListRequestsByUser(ctx context.Context, createdBy string) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SubmittedAt,
			&i.RetrievedAt,
			&i.Ciphertext,
			&i.Iv,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRetrievedAndPurge = `-- name: MarkRetrievedAndPurge :one
UPDATE requests
SET retrieved_at = now(),
    status = 'retrieved',
    ciphertext = NULL,
    iv = NULL
WHERE id = $1
  AND status = 'submitted'
RETURNING id, token, description, created_by, created_at, expires_at,
          submitted_at, retrieved_at, status
`

type MarkRetrievedAndPurgeRow struct {
	ID          uuid.UUID
	Token       string
	Description string
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	SubmittedAt pgtype.Timestamptz
	RetrievedAt pgtype.Timestamptz
	Status      string
}

func (q *Queries) MarkRetrievedAndPurge(ctx context.Context, id uuid.UUID) (MarkRetrievedAndPurgeRow, error) {
	row := q.db.QueryRow(ctx, markRetrievedAndPurge, id)
	var i MarkRetrievedAndPurgeRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Status,
	)
	return i, err
}

const submitCiphertext = `-- name: SubmitCiphertext :one
UPDATE requests
SET ciphertext = $2,
    iv = $3,
    submitted_at = now(),
    status = 'submitted'
WHERE token = $1
  AND status = 'pending'
  AND expires_at > now()
RETURNING id, token, description, created_by, created_at, expires_at,
          submitted_at, retrieved_at, ciphertext, iv, status
`

type SubmitCiphertextParams struct {
	Token      string
	Ciphertext []byte
	Iv         []byte
}

func (q *Queries) SubmitCiphertext(ctx context.Context, arg SubmitCiphertextParams) (Request, error) {
	row := q.db.QueryRow(ctx, submitCiphertext, arg.Token, arg.Ciphertext, arg.Iv)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Ciphertext,
		&i.Iv,
		&i.Status,
	)
	return i, err
}
