// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	DeleteRequest(ctx context.Context, arg DeleteRequestParams) error
	ExpirePendingRequests(ctx context.Context) (int64, error)
	GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error)
	GetRequestByToken(ctx context.Context, token string) (Request, error)
	ListRequestsByUser(ctx context.Context, createdBy string) ([]Request, error)
	MarkRetrievedAndPurge(ctx context.Context, id uuid.UUID) (MarkRetrievedAndPurgeRow, error)
	SubmitCiphertext(ctx context.Context, arg SubmitCiphertextParams) (Request, error)
}

var _ Querier = (*Queries)(nil)
