// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCredentialsByOperator = `-- name: CountCredentialsByOperator :one
SELECT COUNT(*)::int AS n
FROM webauthn_credentials
WHERE operator_id = $1
`

func (q *Queries) CountCredentialsByOperator(ctx context.Context, operatorID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCredentialsByOperator, operatorID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countRequestsByOperator = `-- name: CountRequestsByOperator :one
SELECT COUNT(*)::int AS n
FROM requests
WHERE operator_id = $1
  AND ($2::text = '' OR description ILIKE '%' || $2 || '%')
`

type CountRequestsByOperatorParams struct {
	OperatorID uuid.UUID
	Search     string
}

func (q *Queries) CountRequestsByOperator(ctx context.Context, arg CountRequestsByOperatorParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRequestsByOperator, arg.OperatorID, arg.Search)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countViewsByRequest = `-- name: CountViewsByRequest :one
SELECT COUNT(*)::int AS n
FROM audit_log
WHERE request_id = $1 AND action = 'request.view'
`

func (q *Queries) CountViewsByRequest(ctx context.Context, requestID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countViewsByRequest, requestID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO webauthn_credentials (
    operator_id, credential_id, public_key, sign_count, transports,
    label, aaguid, wrapped_master, wrap_iv
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, operator_id, credential_id, public_key, sign_count, transports,
          label, aaguid, wrapped_master, wrap_iv, created_at, last_used_at
`

type CreateCredentialParams struct {
	OperatorID    uuid.UUID
	CredentialID  []byte
	PublicKey     []byte
	SignCount     int64
	Transports    []string
	Label         string
	Aaguid        []byte
	WrappedMaster []byte
	WrapIv        []byte
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.OperatorID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Label,
		arg.Aaguid,
		arg.WrappedMaster,
		arg.WrapIv,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Label,
		&i.Aaguid,
		&i.WrappedMaster,
		&i.WrapIv,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createOperator = `-- name: CreateOperator :one
INSERT INTO operators (username, email, prf_salt)
VALUES ($1, $2, $3)
RETURNING id, username, email, prf_salt, created_at
`

type CreateOperatorParams struct {
	Username string
	Email    string
	PrfSalt  []byte
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) (Operator, error) {
	row := q.db.QueryRow(ctx, createOperator, arg.Username, arg.Email, arg.PrfSalt)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PrfSalt,
		&i.CreatedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one

INSERT INTO requests (
    token, description, operator_id, expires_at, wrapped_key, wrap_iv, form_schema
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token, description, operator_id, created_at, expires_at,
          submitted_at, retrieved_at, ciphertext, iv, wrapped_key, wrap_iv,
          status, form_schema
`

type CreateRequestParams struct {
	Token       string
	Description string
	OperatorID  uuid.UUID
	ExpiresAt   pgtype.Timestamptz
	WrappedKey  []byte
	WrapIv      []byte
	FormSchema  []byte
}

// =================== requests ===================
func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.Token,
		arg.Description,
		arg.OperatorID,
		arg.ExpiresAt,
		arg.WrappedKey,
		arg.WrapIv,
		arg.FormSchema,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.OperatorID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Ciphertext,
		&i.Iv,
		&i.WrappedKey,
		&i.WrapIv,
		&i.Status,
		&i.FormSchema,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM webauthn_credentials
WHERE id = $1 AND operator_id = $2
`

type DeleteCredentialParams struct {
	ID         uuid.UUID
	OperatorID uuid.UUID
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteCredential, arg.ID, arg.OperatorID)
	return err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = $1 AND operator_id = $2
`

type DeleteRequestParams struct {
	ID         uuid.UUID
	OperatorID uuid.UUID
}

func (q *Queries) DeleteRequest(ctx context.Context, arg DeleteRequestParams) error {
	_, err := q.db.Exec(ctx, deleteRequest, arg.ID, arg.OperatorID)
	return err
}

const expirePendingRequests = `-- name: ExpirePendingRequests :execrows
UPDATE requests
SET status = 'expired'
WHERE status = 'pending'
  AND expires_at <= now()
`

func (q *Queries) ExpirePendingRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredentialByCredentialID = `-- name: GetCredentialByCredentialID :one
SELECT id, operator_id, credential_id, public_key, sign_count, transports,
       label, aaguid, wrapped_master, wrap_iv, created_at, last_used_at
FROM webauthn_credentials
WHERE credential_id = $1
`

func (q *Queries) GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Label,
		&i.Aaguid,
		&i.WrappedMaster,
		&i.WrapIv,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOperatorByID = `-- name: GetOperatorByID :one
SELECT id, username, email, prf_salt, created_at
FROM operators
WHERE id = $1
`

func (q *Queries) GetOperatorByID(ctx context.Context, id uuid.UUID) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByID, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PrfSalt,
		&i.CreatedAt,
	)
	return i, err
}

const getOperatorByUsername = `-- name: GetOperatorByUsername :one

SELECT id, username, email, prf_salt, created_at
FROM operators
WHERE username = $1
`

// =================== operators ===================
func (q *Queries) GetOperatorByUsername(ctx context.Context, username string) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByUsername, username)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PrfSalt,
		&i.CreatedAt,
	)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, token, description, operator_id, created_at, expires_at,
       submitted_at, retrieved_at, ciphertext, iv, wrapped_key, wrap_iv,
       status, form_schema
FROM requests
WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.OperatorID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Ciphertext,
		&i.Iv,
		&i.WrappedKey,
		&i.WrapIv,
		&i.Status,
		&i.FormSchema,
	)
	return i, err
}

const getRequestByToken = `-- name: GetRequestByToken :one
SELECT id, token, description, operator_id, created_at, expires_at,
       submitted_at, retrieved_at, ciphertext, iv, wrapped_key, wrap_iv,
       status, form_schema
FROM requests
WHERE token = $1
`

func (q *Queries) GetRequestByToken(ctx context.Context, token string) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByToken, token)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.OperatorID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Ciphertext,
		&i.Iv,
		&i.WrappedKey,
		&i.WrapIv,
		&i.Status,
		&i.FormSchema,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_log (actor, action, request_id, operator_id, ip, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	Actor      string
	Action     string
	RequestID  *uuid.UUID
	OperatorID *uuid.UUID
	Ip         *netip.Addr
	UserAgent  *string
	Metadata   []byte
}

// =================== audit log ===================
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Actor,
		arg.Action,
		arg.RequestID,
		arg.OperatorID,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}

const listAuditByOperator = `-- name: ListAuditByOperator :many
SELECT id, occurred_at, actor, action, request_id, operator_id, ip, user_agent, metadata
FROM audit_log
WHERE operator_id = $1
ORDER BY occurred_at DESC
LIMIT $2
`

type ListAuditByOperatorParams struct {
	OperatorID *uuid.UUID
	Limit      int32
}

func (q *Queries) ListAuditByOperator(ctx context.Context, arg ListAuditByOperatorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByOperator, arg.OperatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.RequestID,
			&i.OperatorID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByRequest = `-- name: ListAuditByRequest :many
SELECT id, occurred_at, actor, action, request_id, operator_id, ip, user_agent, metadata
FROM audit_log
WHERE request_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListAuditByRequest(ctx context.Context, requestID *uuid.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.RequestID,
			&i.OperatorID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByOperator = `-- name: ListCredentialsByOperator :many

SELECT id, operator_id, credential_id, public_key, sign_count, transports,
       label, aaguid, wrapped_master, wrap_iv, created_at, last_used_at
FROM webauthn_credentials
WHERE operator_id = $1
ORDER BY created_at ASC
`

// =================== webauthn credentials ===================
func (q *Queries) ListCredentialsByOperator(ctx context.Context, operatorID uuid.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByOperator, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.Label,
			&i.Aaguid,
			&i.WrappedMaster,
			&i.WrapIv,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByOperator = `-- name: ListRequestsByOperator :many
SELECT id, token, description, operator_id, created_at, expires_at,
       submitted_at, retrieved_at, ciphertext, iv, wrapped_key, wrap_iv,
       status, form_schema
FROM requests
WHERE operator_id = $1
  AND ($2::text = '' OR description ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListRequestsByOperatorParams struct {
	OperatorID uuid.UUID
	Search     string
	Off        int32
	Lim        int32
}

func (q *Queries) ListRequestsByOperator(ctx context.Context, arg ListRequestsByOperatorParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByOperator,
		arg.OperatorID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Description,
			&i.OperatorID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SubmittedAt,
			&i.RetrievedAt,
			&i.Ciphertext,
			&i.Iv,
			&i.WrappedKey,
			&i.WrapIv,
			&i.Status,
			&i.FormSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRetrievedAndPurge = `-- name: MarkRetrievedAndPurge :one
UPDATE requests
SET retrieved_at = now(),
    status = 'retrieved',
    ciphertext = NULL,
    iv = NULL,
    wrapped_key = NULL,
    wrap_iv = NULL
WHERE id = $1
  AND status = 'submitted'
RETURNING id, token, description, operator_id, created_at, expires_at,
          submitted_at, retrieved_at, status
`

type MarkRetrievedAndPurgeRow struct {
	ID          uuid.UUID
	Token       string
	Description string
	OperatorID  uuid.UUID
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	SubmittedAt pgtype.Timestamptz
	RetrievedAt pgtype.Timestamptz
	Status      string
}

func (q *Queries) MarkRetrievedAndPurge(ctx context.Context, id uuid.UUID) (MarkRetrievedAndPurgeRow, error) {
	row := q.db.QueryRow(ctx, markRetrievedAndPurge, id)
	var i MarkRetrievedAndPurgeRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.OperatorID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Status,
	)
	return i, err
}

const pruneAuditOlderThan = `-- name: PruneAuditOlderThan :execrows
DELETE FROM audit_log WHERE occurred_at < $1
`

func (q *Queries) PruneAuditOlderThan(ctx context.Context, occurredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuditOlderThan, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const submitCiphertext = `-- name: SubmitCiphertext :one
UPDATE requests
SET ciphertext = $2,
    iv = $3,
    submitted_at = now(),
    status = 'submitted'
WHERE token = $1
  AND status = 'pending'
  AND expires_at > now()
RETURNING id, token, description, operator_id, created_at, expires_at,
          submitted_at, retrieved_at, ciphertext, iv, wrapped_key, wrap_iv,
          status, form_schema
`

type SubmitCiphertextParams struct {
	Token      string
	Ciphertext []byte
	Iv         []byte
}

func (q *Queries) SubmitCiphertext(ctx context.Context, arg SubmitCiphertextParams) (Request, error) {
	row := q.db.QueryRow(ctx, submitCiphertext, arg.Token, arg.Ciphertext, arg.Iv)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.OperatorID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.RetrievedAt,
		&i.Ciphertext,
		&i.Iv,
		&i.WrappedKey,
		&i.WrapIv,
		&i.Status,
		&i.FormSchema,
	)
	return i, err
}

const updateCredentialAfterUse = `-- name: UpdateCredentialAfterUse :exec
UPDATE webauthn_credentials
SET sign_count = $2,
    last_used_at = now()
WHERE id = $1
`

type UpdateCredentialAfterUseParams struct {
	ID        uuid.UUID
	SignCount int64
}

func (q *Queries) UpdateCredentialAfterUse(ctx context.Context, arg UpdateCredentialAfterUseParams) error {
	_, err := q.db.Exec(ctx, updateCredentialAfterUse, arg.ID, arg.SignCount)
	return err
}

const setCredentialWrappedMaster = `-- name: SetCredentialWrappedMaster :execrows
UPDATE webauthn_credentials
SET wrapped_master = $3,
    wrap_iv        = $4
WHERE id = $1 AND operator_id = $2
  AND wrapped_master IS NULL
`

type SetCredentialWrappedMasterParams struct {
	ID            uuid.UUID
	OperatorID    uuid.UUID
	WrappedMaster []byte
	WrapIv        []byte
}

func (q *Queries) SetCredentialWrappedMaster(ctx context.Context, arg SetCredentialWrappedMasterParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCredentialWrappedMaster, arg.ID, arg.OperatorID, arg.WrappedMaster, arg.WrapIv)
	return result.RowsAffected(), err
}

const upsertOperator = `-- name: UpsertOperator :one
INSERT INTO operators (username, email, prf_salt)
VALUES ($1, $2, $3)
ON CONFLICT (username) DO UPDATE
  SET email = EXCLUDED.email
RETURNING id, username, email, prf_salt, created_at
`

type UpsertOperatorParams struct {
	Username string
	Email    string
	PrfSalt  []byte
}

func (q *Queries) UpsertOperator(ctx context.Context, arg UpsertOperatorParams) (Operator, error) {
	row := q.db.QueryRow(ctx, upsertOperator, arg.Username, arg.Email, arg.PrfSalt)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PrfSalt,
		&i.CreatedAt,
	)
	return i, err
}
